import { useState, useRef, useEffect } from 'react'
import axios from 'axios'
import './KnowledgeChatbot.css'

const API_URL = 'http://localhost:8000/knowledge-chat'

const SUGGESTIONS = [
'How do I upload an X-ray in PneumaVision? ' ,
'Which doctor should I consult for Pneumonia?'  ,
'What is Cardiomegaly?'  ,
'How is Fibrosis detected on chest X-ray?'  ,
'Explain the report generated by PneumaVision'  ,
'What precautions should I take for Emphysema?'  
]

export default function KnowledgeChatbot() {
  const [messages, setMessages] = useState([
    {
      role: 'assistant',
     text: `Hi! I'm your PneumaVision assistant. I can help you with:
• Understanding the 14 chest conditions detected by PneumaVision  
• Step-by-step guidance on using the platform  
• Doctor profiles and medical specializations `,
    },
  ])
  const [input,   setInput]   = useState('')
  const [loading, setLoading] = useState(false)
  const bottomRef = useRef(null)
  const inputRef  = useRef(null)

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  const buildHistory = (msgs) =>
    msgs
      .slice(1)
      .map(m => ({
        role:  m.role === 'assistant' ? 'model' : 'user',
        parts: [m.text],
      }))

  const sendMessage = async (text) => {
    const question = text.trim()
    if (!question || loading) return

    const userMsg     = { role: 'user', text: question }
    const updatedMsgs = [...messages, userMsg]
    setMessages(updatedMsgs)
    setInput('')
    setLoading(true)

    try {
      const { data } = await axios.post(API_URL, {
        question,
        history: buildHistory(updatedMsgs),
      })
      setMessages(prev => [...prev, { role: 'assistant', text: data.answer }])
    } catch {
      setMessages(prev => [
        ...prev,
        {
          role: 'assistant',
          text: '⚠️ Could not reach the server. Please make sure the backend is running.',
        },
      ])
    } finally {
      setLoading(false)
    }
  }

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage(input)
    }
  }

const handleClear = () => {
  setMessages([{
    role: 'assistant',
     text: `Hi! I'm your PneumaVision assistant. I can help you with:
• Understanding the 14 chest conditions detected by PneumaVision  
• Step-by-step guidance on using the platform  
• Doctor profiles and medical specializations `,
  }])

  setInput('')
}

  return (
    <aside className="kcb">

      {/* ── Header ── */}
      <div className="kcb-header">
        <div className="kcb-header-left">
          <div className="kcb-avatar">✚</div>
          <div>
            <div className="kcb-title">PneumaVision Assistant</div>
            <div className="kcb-subtitle">Smart Knowledge Base · AI Health Support</div>
          </div>
        </div>
        <button className="kcb-clear" onClick={handleClear} title="Clear chat">
          ↺
        </button>
      </div>

      {/* ── Messages ── */}
      <div className="kcb-messages">
        {messages.map((m, i) => (
          <div key={i} className={`kcb-msg kcb-msg--${m.role}`}>
            {m.role === 'assistant' && (
              <div className="kcb-msg-avatar">✚</div>
            )}
            <div className="kcb-msg-bubble">{m.text}</div>
          </div>
        ))}

        {loading && (
          <div className="kcb-msg kcb-msg--assistant">
            <div className="kcb-msg-avatar">✚</div>
            <div className="kcb-msg-bubble kcb-typing">
              <span /><span /><span />
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      {/* ── Suggestions ── */}
      {messages.length === 1 && (
        <div className="kcb-suggestions">
          {SUGGESTIONS.map(s => (
            <button
              key={s}
              className="kcb-suggestion"
              onClick={() => sendMessage(s)}
            >
              {s}
            </button>
          ))}
        </div>
      )}

      {/* ── Input ── */}
      <div className="kcb-input-row">
        <textarea
          ref={inputRef}
          className="kcb-input"
          placeholder="Ask about any chest condition…"
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          rows={1}
          disabled={loading}
        />
        <button
          className="kcb-send"
          onClick={() => sendMessage(input)}
          disabled={!input.trim() || loading}
        >
          ↑
        </button>
      </div>

    </aside>
  )
}